comment: True

coverage:
  range: 50..100
  round: down
  precision: 2
  status:
    project:
      default: off
      src:
        paths: distriopt/
        enabled: yes
        target: 50
        threshold: 5
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        informational: true
    changes: false