language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

branches:
  only:
    - master

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq glpk-utils

install:
  - pip install -r requirements.txt
  - pip install pytest

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - pytest -v tests