dist: xenial
language: python
python:
    - 3.6
    - 3.7
    #- pypy3.6-7.1.1

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq glpk-utils

cache: pip

install:
  - pip install -r requirements.txt
  - pip install pytest

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - pytest -v tests

notifications:
  email:
    recipients:
      - andrea.tomassilli@inria.fr
    on_success: never
    on_failure: never